esphome:
  name: five-in-one-sensor-example
  friendly_name: 21VOC Sensor Example

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# UART configuration for the sensor (9600 baud, 8N1)
uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

# External components - update the source path as needed
external_components:
  - source:
      type: local
      path: components

# 21VOC Sensor configuration
sensor:
  - platform: five_in_one_sensor
    voc:
      name: "VOC"
      id: voc_sensor
    formaldehyde:
      name: "Formaldehyde"
      id: formaldehyde_sensor
    eco2:
      name: "eCO2"
      id: eco2_sensor
    temperature:
      name: "Temperature"
      id: temperature_sensor
    humidity:
      name: "Humidity"
      id: humidity_sensor
